#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

#Adding this section for displaying code metrics to console
echo "===== TESTING CODE COVERAGE ====="
pwd
cd Project
coverage run --source=home,mysite,accounts,goals manage.py test
coverage report
echo "===== END TESTING METRICS ====="