version: 2
permissions:
  contents: write
  pull-requests: write
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    commit-message:
      prefix: "deps"
      include: "scope"
