# Generated by Django 4.2.11 on 2025-04-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(max_length=100, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='target',
            field=models.CharField(max_length=100, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(max_length=100, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
