# Generated by Django 4.2.11 on 2025-03-26 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_userexercise_percent_increase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='planned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
