# Generated by Django 4.2.11 on 2025-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_userexercise_planned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexercise',
            old_name='planned_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='userexercise',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='recurring_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
