# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring, R0801

"""
Initial migration to create the UserData and UserProfile models, with related fields for tracking 
user data, fitness level, goals, and injury history. It links the UserProfile to the built-in 
User model with a OneToOne relationship, and associates UserData with the User model through a 
ForeignKey relationship.
"""

# Generated by Django 5.1.6 on 2025-03-09 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create UserData and UserProfile models with fields for user tracking and
     a relationship to the User model."""
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("bmi", models.FloatField(blank=True, null=True)),
                (
                    "fitness_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("goals", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmi", models.FloatField(blank=True, null=True)),
                (
                    "fitness_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("goals", models.TextField(blank=True, null=True)),
                ("injury_history", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
