# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring
"""
Migration to add 'height' and 'weight' fields to the UserProfile model.
"""
# Generated by Django 5.1.6 on 2025-03-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    """Defines the operations for adding height and weight fields to UserProfile."""
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
