# pylint: disable=E0401, E0611, E1101, C0114, C0115, C0301, C0103
# Generated by Django 5.1.6 on 2025-03-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(
                blank=True, help_text="Height in centimeters", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Weight in kilograms", null=True
            ),
        ),
    ]
