# Generated by Django 5.1.6 on 2025-03-12 21:42
# pylint: disable=all
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(
                blank=True, help_text="Height in centimeters", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Weight in kilograms", null=True
            ),
        ),
    ]
