# Generated by Django 5.1.6 on 2025-03-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_height_userprofile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner – New to exercise or returning after a long break. Low endurance, strength, and flexibility.'), ('intermediate', 'Intermediate – Engages in regular physical activity (e.g., 1-3 times per week), has moderate endurance and strength.'), ('advanced', 'Advanced – High fitness level with consistent training (e.g., 3+ times per week), strong endurance, strength, and flexibility.'), ('athlete', 'Athlete – Trains for specific performance goals (e.g., competitive sports, weightlifting, endurance events).'), ('rehab', 'Rehabilitation/Recovery – Focused on regaining fitness after an injury, surgery, or medical condition.'), ('senior', 'Senior/Low Impact – Prioritizes joint-friendly and lower-intensity movements, often for older adults or those with physical limitations.')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='injury_history',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.ManyToManyField(blank=True, to='accounts.goal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='injury_history',
            field=models.ManyToManyField(blank=True, to='accounts.injury'),
        ),
    ]
