# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring, R0801

"""
Migration to modify the 'userdata' model:
- Adds 'height' and 'weight' fields.
- Removes the 'date' field.
- Modifies the 'fitness_level' field to reference a new 'FitnessLevel' model.
- Changes the 'goals' field to a ManyToMany relationship.
"""

# Generated by Django 5.1.6 on 2025-03-12 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Modify the 'userdata' model by adding 'height' and 'weight' fields, removing
    'date', and updating 'fitness_level' and 'goals'."""

    dependencies = [
        ("accounts", "0003_goal_injury_alter_userprofile_fitness_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="date",
        ),
        migrations.AddField(
            model_name="userdata",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="goals",
        ),
        migrations.AlterField(
            model_name="userdata",
            name="fitness_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.fitnesslevel",
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="goals",
            field=models.ManyToManyField(to="accounts.goal"),
        ),
    ]
