# pylint: disable=E0401, E0611, E1101, C0114, C0115, C0301, C0103
# Generated by Django 4.2.11 on 2025-03-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_fitnesslevel_remove_userdata_date_userdata_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(
                blank=True, help_text="Height in inches", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Weight in pounds", null=True
            ),
        ),
        migrations.DeleteModel(
            name="UserData",
        ),
    ]
