# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring

"""
Migration to alter the 'userprofile' model:
- Modifies 'height' and 'weight' fields by adding help text for user clarification.
- Deletes the 'UserData' model.
"""

# Generated by Django 4.2.11 on 2025-03-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    """Alter 'userprofile' model fields and delete 'UserData' model."""
    dependencies = [
        ("accounts", "0004_fitnesslevel_remove_userdata_date_userdata_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(
                blank=True, help_text="Height in inches", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Weight in pounds", null=True
            ),
        ),
        migrations.DeleteModel(
            name="UserData",
        ),
    ]
