# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring, R0801

"""
Migration to add a weight history field to the UserProfile model.
This field tracks the user's weight and categorizes their fitness level.
"""

# Generated by Django 4.2.11 on 2025-04-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add weight history field to the UserProfile model to track user's fitness progress."""

    dependencies = [
        ("accounts", "0005_alter_userprofile_height_alter_userprofile_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="weight_history",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "beginner",
                        "Beginner – New to exercise or returning after a long break.\
                            Low endurance, strength, and flexibility.",
                    ),
                    (
                        "intermediate",
                        "Intermediate – Engages in regular physical activity\
                            (e.g., 1-3 times per week), has moderate endurance and strength.",
                    ),
                    (
                        "advanced",
                        "Advanced – High fitness level with consistent training\
                            (e.g., 3+ times per week), strong endurance, strength,\
                                and flexibility.",
                    ),
                    (
                        "athlete",
                        "Athlete – Trains for specific performance goals\
                            (e.g., competitive sports, weightlifting, endurance events).",
                    ),
                    (
                        "rehab",
                        "Rehabilitation/Recovery – Focused on regaining fitness after an\
                            injury, surgery, or medical condition.",
                    ),
                    (
                        "senior",
                        "Senior/Low Impact – Prioritizes joint-friendly and lower-intensity\
                            movements, often for older adults or those with physical limitations.",
                    ),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
