# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring, line-too-long

"""
Migration to add the 'friends' field and create 'FriendRequest' model:
- Adds a 'friends' field (ManyToMany relationship) to 'userprofile' model.
- Creates a new 'FriendRequest' model to represent friend requests between users.
"""

# Generated by Django 4.2.11 on 2025-04-04 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Add 'friends' field and create 'FriendRequest' model for user relationships."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_alter_userprofile_height_alter_userprofile_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="accounts.userprofile"),
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
