# pylint: disable=E0401, E0611, E1101, C0114, C0115, C0301, C0103
# Generated by Django 4.2.11 on 2025-04-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_userprofile_weight_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sets", models.IntegerField(default=0)),
                ("reps", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
            ],
        ),
    ]
