# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring, R0801

"""
Migration to create the UserExercise model.
This model tracks user-specific exercise data including name, sets, reps, and weight.
"""

# Generated by Django 4.2.11 on 2025-04-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the UserExercise model to store individual exercise data for users."""
    dependencies = [
        ("accounts", "0006_userprofile_weight_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sets", models.IntegerField(default=0)),
                ("reps", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
            ],
        ),
    ]
