# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring
"""
Migration to change the 'id' field of the UserAccExercise model to use AutoField instead
of BigAutoField.
"""

# Generated by Django 4.2.11 on 2025-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    """Alters the ID field in the UserAccExercise model to use AutoField."""
    dependencies = [
        ('accounts', '0008_useraccexercise_delete_userexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccexercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
