# Generated by Django 4.2.11 on 2025-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useraccexercise_delete_userexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccexercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
