# pylint: disable=E0401, E0611, E1101, C0114, C0115, C0301, C0103
# # Generated by Django 4.2.11 on 2025-04-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_alter_useraccexercise_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccexercise",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
