# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring, line-too-long

"""
Migration to alter the 'user' field in the UserAccExercise model from OneToOneField to ForeignKey.
"""

# Generated by Django 4.2.11 on 2025-04-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Updates the user field in UserAccExercise to allow multiple related records (ForeignKey)."""
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_alter_useraccexercise_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccexercise",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
