# pylint: disable=E0401, E0611, E1101, C0114, C0115, C0301, C0103
# Generated by Django 4.2.11 on 2025-04-08 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_userprofile_friends_friendrequest"),
        ("accounts", "0010_alter_useraccexercise_user"),
    ]

    operations = []
