# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring

"""
Migration to merge changes from migrations 0006_userprofile_friends_friendrequest and 0010_alter_useraccexercise_user.
This ensures both branches of the migration history are reconciled before further changes.
"""

# Generated by Django 4.2.11 on 2025-04-08 15:09

from django.db import migrations


class Migration(migrations.Migration):
    """Merge migration to unify divergent migration paths."""
    dependencies = [
        ('accounts', '0006_userprofile_friends_friendrequest'),
        ('accounts', '0010_alter_useraccexercise_user'),
    ]

    operations = [
    ]
