# Generated by Django 4.2.11 on 2025-04-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_friends_friendrequest'),
        ('accounts', '0010_alter_useraccexercise_user'),
    ]

    operations = [
    ]
