# pylint: disable=E0401, E0611, E1101, C0114, C0115, C0301, C0103
# Generated by Django 4.2.11 on 2025-04-16 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0011_merge_20250408_1509"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodDatabase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("barcode", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
                ("carbs", models.IntegerField(default=0)),
                ("protein", models.IntegerField(default=0)),
                ("fat", models.IntegerField(default=0)),
                ("servings", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
