# Generated by Django 4.2.11 on 2025-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_fooddatabase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooddatabase",
            name="carbs",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="fooddatabase",
            name="fat",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="fooddatabase",
            name="protein",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="fooddatabase",
            name="servings",
            field=models.FloatField(default=0),
        ),
    ]
