# Generated by Django 4.2.11 on 2025-04-16 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_fooddatabase_carbs_alter_fooddatabase_fat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooddatabase",
            name="datelog",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
