# pylint: disable=invalid-name, missing-module-docstring, missing-class-docstring

"""
Migration to add a date log field to the FoodDatabase model.
This field tracks the date when an entry in the food database was logged.
"""

# Generated by Django 4.2.11 on 2025-04-16 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add a datelog field to the FoodDatabase model to track entry logging date."""
    dependencies = [
        ('accounts', '0013_alter_fooddatabase_carbs_alter_fooddatabase_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddatabase',
            name='datelog',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
