name: AI Pull Request Review
on:
  pull_request:
    types:
      - opened
jobs:
  deploy:
    name: OpenAI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
         
      - uses: sshnaidm/gpt-code-review-action@v2.1
        with:
          openai-key: ${{ secrets.OPENAIAPI }}
          model: 'gpt-4'
          max-length: 8000
          prompt: 'Explain what changes are occuring with this code.'
