name: AI Pull Request Review
on:
  pull_request:
    types:
      - opened
jobs:
  deploy:
    name: OpenAI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get PR Diff
        uses: GrantBirki/git-diff-action@vX.X.X
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"
          env:
            DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
        -name: OpenAI
          with:
            openai-api-key: ${{ secrets.OPENAIAPI }}
            openai-prompt: "Explain the differences of the given diff file to tell me what changes have occured in a pretty format: ${{ steps.git-diff-action.outputs.raw-diff-path }}"
            model: gpt-4
