name: AI Pull Request Review
on:
  pull_request:
    types:
      - opened
jobs:
  deploy:
    name: OpenAI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get PR Diff
        uses: GrantBirki/git-diff-action@v2.5.0
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"
      - name: OpenAI
        uses: riccardolinares/openai-commit@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-prompt: "Review the changes in this diff file and tell me whats going on: \n${{ steps.git-diff-action.outputs.raw-diff-path }}"
        id: openai
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: openai
          path: code_review.txt
