name: Django Test CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd Project
        python3 manage.py test
    - name: Run Pylint
      run: |
        pylint Project > pylint_output.txt
    - name: Upload Pylint Report
      uses: actions/upload-artifact@v4
      with:
        name: pylint-report
        path: pylint_output.txt

